# Deploys  django polls application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - image: "hello-world:1.0"
        name: hello-world
        resources:
            requests:
              memory: "32Mi"
              cpu: "125m"
            limits:
              memory: "64Mi"
              cpu: "0.5"
        imagePullPolicy: Never # only for minikube builds where #eval(minikube docker-env) is used
---
apiVersion: v1
kind: Service
metadata:
  name: python-app
  labels:
    app: python-app
spec:
  type: NodePort
  ports:
   - port: 81
  selector:
   app: hello-world